### ISSUE TITLE
Should this be OceanParameterizations or ClimateParameterizations?

### ISSUE THREAD

**Issue by glwagner** [CliMA/OceanParameterizations.jl#14]
It's not totally clear what a "climate parameterization" is. It's too broad, because it can encompass everything from the absorption of radiation to models of human psychology :-O

I think this package has the potential to became practically useful for oceanography, for example (superceding `OceanTurb`). I think ClimateParameterizations might obfuscate the functionality of this package and make it harder to find by the people who might benefit from it.

If we want to cover parameterizations relevant to atmospheric models as well, then we can try to come up with a name that encompasses oceans and atmospheres (planetary fluids...) Climate is much broader even than just ocean and atmospheres, though.

**Comment by glwagner** [comment]
Now that this repo is more visible because it is part of the CliMA organization, this issue is relatively high priority.

**Comment by ali-ramadhan** [comment]
I agree. Will do it now. I'll just passive aggressively leave this here though lol.

![tmp](https://user-images.githubusercontent.com/20099589/101221475-c62ead80-3655-11eb-9001-7914ba30ca6c.png)

**Comment by ChrisRackauckas** [comment]
Gottem.
