### ISSUE TITLE
Change RegularCartesianGrid to RegularRectilinearGrid

### ISSUE THREAD

**Issue by xkykai** [CliMA/OceanParameterizations.jl#47]
Breaking change in `Oceananigans.jl v0.50.0` to change `RegularCartesianGrid` to `RegularRectilinearGrid`

https://github.com/CliMA/OceanParameterizations.jl/blob/2bb2ab85a30962567694f8440f7a999c33219811/free_convection/src/oceananigans_nn.jl#L62

**Comment by ali-ramadhan** [comment]
I think this has been done in one of your PRs so I'll close this issue.
